-- MySQL Script generated by MySQL Workbench
-- Fri Aug 24 17:35:19 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Student` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Student` (
  `studentID` INT NOT NULL,
  `studentName` VARCHAR(45) NULL,
  `loginPassword` VARCHAR(45) NULL,
  PRIMARY KEY (`studentID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Lecture`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Lecture` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Lecture` (
  `lectureID` INT NOT NULL,
  `lectureName` VARCHAR(45) NULL,
  PRIMARY KEY (`lectureID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Course` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Course` (
  `courseID` VARCHAR(10) NOT NULL,
  `courseName` VARCHAR(45) NULL,
  `startDate` DATETIME NULL,
  `endDate` DATETIME NULL,
  `startTime` DATETIME NULL,
  `endTime` DATETIME NULL,
  `room` VARCHAR(5) NULL,
  `Lecture_lectureID` INT NOT NULL,
  PRIMARY KEY (`courseID`),
  INDEX `fk_Course_Lecture1_idx` (`Lecture_lectureID` ASC),
  CONSTRAINT `fk_Course_Lecture1`
    FOREIGN KEY (`Lecture_lectureID`)
    REFERENCES `mydb`.`Lecture` (`lectureID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Assignment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Assignment` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Assignment` (
  `assignmentID` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `dueDate` DATETIME NULL,
  `Course_courseID` INT NOT NULL,
  PRIMARY KEY (`Course_courseID`, `assignmentID`),
  INDEX `fk_Assignment_Course1_idx` (`Course_courseID` ASC),
  CONSTRAINT `fk_Assignment_Course1`
    FOREIGN KEY (`Course_courseID`)
    REFERENCES `mydb`.`Course` (`courseID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Test`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Test` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Test` (
  `testID` INT NOT NULL,
  `testName` VARCHAR(45) NULL,
  `testDate` DATETIME NULL,
  `Course_courseID` INT NOT NULL,
  PRIMARY KEY (`Course_courseID`, `testID`),
  INDEX `fk_Test_Course_idx` (`Course_courseID` ASC),
  CONSTRAINT `fk_Test_Course`
    FOREIGN KEY (`Course_courseID`)
    REFERENCES `mydb`.`Course` (`courseID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Campus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Campus` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Campus` (
  `CampusID` INT NOT NULL,
  `campusName` VARCHAR(45) NULL,
  `campusCode` VARCHAR(5) NULL,
  `address` VARCHAR(45) NULL,
  PRIMARY KEY (`CampusID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Session`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Session` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Session` (
  `sessionID` INT NOT NULL,
  `topic` VARCHAR(45) NULL,
  `sessionDate` DATETIME NULL,
  `Course_courseID` INT NOT NULL,
  PRIMARY KEY (`Course_courseID`, `sessionID`),
  INDEX `fk_Session_Course1_idx` (`Course_courseID` ASC),
  CONSTRAINT `fk_Session_Course1`
    FOREIGN KEY (`Course_courseID`)
    REFERENCES `mydb`.`Course` (`courseID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Campus_has_Course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Campus_has_Course` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Campus_has_Course` (
  `Campus_CampusID` INT NOT NULL,
  `Course_courseID` INT NOT NULL,
  PRIMARY KEY (`Campus_CampusID`, `Course_courseID`),
  INDEX `fk_Campus_has_Course_Course1_idx` (`Course_courseID` ASC),
  INDEX `fk_Campus_has_Course_Campus1_idx` (`Campus_CampusID` ASC),
  CONSTRAINT `fk_Campus_has_Course_Campus1`
    FOREIGN KEY (`Campus_CampusID`)
    REFERENCES `mydb`.`Campus` (`CampusID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Campus_has_Course_Course1`
    FOREIGN KEY (`Course_courseID`)
    REFERENCES `mydb`.`Course` (`courseID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Course_has_Student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Course_has_Student` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Course_has_Student` (
  `Course_courseID` INT NOT NULL,
  `Student_studentID` INT NOT NULL,
  PRIMARY KEY (`Course_courseID`, `Student_studentID`),
  INDEX `fk_Course_has_Student_Student1_idx` (`Student_studentID` ASC),
  INDEX `fk_Course_has_Student_Course1_idx` (`Course_courseID` ASC),
  CONSTRAINT `fk_Course_has_Student_Course1`
    FOREIGN KEY (`Course_courseID`)
    REFERENCES `mydb`.`Course` (`courseID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Course_has_Student_Student1`
    FOREIGN KEY (`Student_studentID`)
    REFERENCES `mydb`.`Student` (`studentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
