-- MySQL Script generated by MySQL Workbench
-- Sat Sep  8 10:30:17 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Student` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Student` (
  `studentID` INT NOT NULL,
  `studentName` VARCHAR(45) NULL,
  `loginPassword` VARCHAR(45) NULL,
  PRIMARY KEY (`studentID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Lecture`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Lecture` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Lecture` (
  `lectureID` INT NOT NULL,
  `lectureName` VARCHAR(45) NULL,
  PRIMARY KEY (`lectureID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Subject`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Subject` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Subject` (
  `subjectID` INT NOT NULL,
  `subjectCode` VARCHAR(45) NULL,
  `subjectName` VARCHAR(45) NULL,
  PRIMARY KEY (`subjectID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Campus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Campus` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Campus` (
  `CampusID` INT NOT NULL,
  `campusName` VARCHAR(45) NULL,
  `campusCode` VARCHAR(5) NULL,
  `address` VARCHAR(45) NULL,
  PRIMARY KEY (`CampusID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Class`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Class` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Class` (
  `classID` INT NOT NULL,
  `Lecture_lectureID` INT NOT NULL,
  `Subject_subjectID` INT NOT NULL,
  `Campus_CampusID` INT NOT NULL,
  PRIMARY KEY (`classID`),
  INDEX `fk_Class_Lecture1_idx` (`Lecture_lectureID` ASC),
  INDEX `fk_Class_Subject1_idx` (`Subject_subjectID` ASC),
  INDEX `fk_Class_Campus1_idx` (`Campus_CampusID` ASC),
  CONSTRAINT `fk_Class_Lecture1`
    FOREIGN KEY (`Lecture_lectureID`)
    REFERENCES `mydb`.`Lecture` (`lectureID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Class_Subject1`
    FOREIGN KEY (`Subject_subjectID`)
    REFERENCES `mydb`.`Subject` (`subjectID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Class_Campus1`
    FOREIGN KEY (`Campus_CampusID`)
    REFERENCES `mydb`.`Campus` (`CampusID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Assessment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Assessment` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Assessment` (
  `assessmentID` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `dueDate` DATE NULL,
  `type` VARCHAR(10) NULL,
  `Class_classID` INT NOT NULL,
  INDEX `fk_Assessment_Class1_idx` (`Class_classID` ASC),
  PRIMARY KEY (`assessmentID`),
  CONSTRAINT `fk_Assessment_Class1`
    FOREIGN KEY (`Class_classID`)
    REFERENCES `mydb`.`Class` (`classID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Session`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Session` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Session` (
  `sessionID` INT NOT NULL,
  `sessionNo` INT NULL,
  `topic` VARCHAR(45) NULL,
  `startTime` TIME NULL,
  `endTime` TIME NULL,
  `room` VARCHAR(6) NULL,
  `date` DATE NULL,
  `Class_classID` INT NOT NULL,
  INDEX `fk_Session_Class1_idx` (`Class_classID` ASC),
  PRIMARY KEY (`sessionID`),
  CONSTRAINT `fk_Session_Class1`
    FOREIGN KEY (`Class_classID`)
    REFERENCES `mydb`.`Class` (`classID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Class_has_Student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Class_has_Student` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Class_has_Student` (
  `Class_classID` INT NOT NULL,
  `Class_Subject_subjectID` INT NOT NULL,
  `Student_studentID` INT NOT NULL,
  PRIMARY KEY (`Class_classID`, `Class_Subject_subjectID`, `Student_studentID`),
  INDEX `fk_Class_has_Student_Student1_idx` (`Student_studentID` ASC),
  INDEX `fk_Class_has_Student_Class1_idx` (`Class_classID` ASC, `Class_Subject_subjectID` ASC),
  CONSTRAINT `fk_Class_has_Student_Class1`
    FOREIGN KEY (`Class_classID` , `Class_Subject_subjectID`)
    REFERENCES `mydb`.`Class` (`classID` , `Subject_subjectID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Class_has_Student_Student1`
    FOREIGN KEY (`Student_studentID`)
    REFERENCES `mydb`.`Student` (`studentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
